mode: predict
debug: False
load_ckpt: experiments/vm_strong/checkpoint_39.pkl

components:
  data: predict
  transform: predict
  system: vm
  model: vm_strong_E9

writer:
  __target__: vm
  save_dir: tmp_predict
  save_name: denoised
