mode: predict
debug: False
load_ckpt: experiments/vm_sprint_recovery/checkpoint_selected.pkl

components:
  data: predict_val
  transform: predict
  system: vm
  model: vm_sprint_recovery_selected

writer:
  __target__: vm
  save_dir: tmp_predict_val_recovery
  save_name: denoised
